version: "3"

services:
  node:
    build:
      context: .
    volumes:
      - "./:/src/app"
    ports:
      - "3030:3000"
    links:
      - rethinkdb

  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
